spring:
  application:
    name: SPS-ACAD-SAPTITLE
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin   
  datasource:
    url: jdbc:mysql://GBSMIXDEV01.UK.OUP.COM:3306/sps
    username: SMIXDBUser
    password: P@ssw0rd1!
    driver-class-name: com.mysql.jdbc.Driver
      
server:
  port: 8080  
eureka:
  client:
    enabled: false

camel:
  springboot:
    main-run-controller: true
    
activemq:
    uk:
      queuename: SPS-ACAD-UK-AC18-SAP-TITLES-DEV
      corntab:
        timezone: Europe/London
        starttime: 0 47 14 ? * * *
        stoptime: 0 50 14 ? * * *
    us:
      queuename: SPS-ACAD-US-US18-SAP-TITLES-DEV
      corntab:
        timezone: US/Hawaii
        starttime: 0 57 3 ? * * *
        stoptime: 0 59 3 ? * * *

file:
  backup:
    location: C:\\JavaTest\\SPS\\AC18_SAPTitle\\   
       
ftp:
  uk: 
    server: GBOXFFTPWIN
    port: 21
    username: ftpunix
    password: 12Xdirect
    drop:
      location: /acad_abc_dev/Export
  us: 
    server: GBOXFFTPWIN
    port: 21
    username: ftpunix
    password: 12Xdirect
    drop:
      location: /acad_abc_dev/Export
management:
  security:
    enabled: false
  metrics:
    export:
      prometheus: 
        enabled: true
    distribution:
      percentiles[http.server.requests]: 0.95, 0.99
      percentiles-histogram[http.server.requests]: true
      sla[http.server.requests]: 10ms, 100ms
---
spring:
  profiles: dev
  activemq:
    broker-url: tcp://gbsmixdev01.uk.oup.com:63636
    user: servicemix
    password: servicemix@1234
  datasource:
    url: jdbc:mysql://GBSMIXDEV01.UK.OUP.COM:3306/sps
    username: SMIXDBUser
    password: P@ssw0rd1!
    driver-class-name: com.mysql.jdbc.Driver

activemq:
    uk:
      queuename: queue:SPS-ACAD-UK-AC18-SAP-TITLES-DEV
      corntab:
        timezone: Europe/London
        starttime: 0 0,10,20,30,40,50 * * * ? *
        stoptime: 0 9,19,29,39,49,59 * * * ? *
    us:
      queuename: SPS-ACAD-US-US18-SAP-TITLES-DEV
      corntab:
        timezone: US/Hawaii
        starttime: 0 0,10,20,30,40,50 * * * ? *
        stoptime: 0 9,19,29,39,49,59 * * * ? *
      
file:
  backup:
    location: /OUT/SPS/${spring.application.name}/dev
    
ftp:
  uk: 
    server: GBOXFFTPWIN
    port: 21
    username: ftpunix
    password: 12Xdirect
    drop:
      location: /acad_abc_dev/Export
  us: 
    server: GBOXFFTPWIN
    port: 21
    username: ftpunix
    password: 12Xdirect
    drop:
      location: /acad_abc_dev/Export
    
eureka:
  client:
    enabled: true
    service-url:  
      defaultZone: http://dev-oupeureka:8761/eureka/
  instance:
    prefer-ip-address: true   
management:
  security:
    enabled: false
  metrics:
    export:
      prometheus: 
        enabled: true
    distribution:
      percentiles[http.server.requests]: 0.95, 0.99
      percentiles-histogram[http.server.requests]: true
      sla[http.server.requests]: 10ms, 100ms    
---
spring:
  profiles: uat
  activemq:
    broker-url: tcp://gboxfamqdev001.uk.oup.com:61616
    user: servicemix
    password: servicemix@1234
  datasource:
    url: jdbc:mysql://GBSMIXUAT01.UK.OUP.COM:3306/sps
    username: SMIXDBUser
    password: P@ssw0rd1!
    driver-class-name: com.mysql.jdbc.Driver
  
activemq:
    uk:
      queuename: queue:SPS-ACAD-UK-AC18-SAP-TITLES-QA
      corntab:
        timezone: Europe/London
        starttime: 0 0,10,20,30,40,50 * * * ? *
        stoptime: 0 9,19,29,39,49,59 * * * ? *
    us:
      queuename: queue:SPS-ACAD-US-US18-SAP-TITLES-QA
      corntab:
        timezone: US/Hawaii
        starttime: 0 0,10,20,30,40,50 * * * ? *
        stoptime: 0 9,19,29,39,49,59 * * * ? *
        
file:
  backup:
    location: /OUT/SPS/${spring.application.name}/uat
    
ftp:
  uk: 
    server: GBOXFFTPWIN
    port: 21
    username: ftpunix
    password: 12Xdirect
    drop:
      location: /acad_abc_qa/Export
  us: 
    server: GBOXFFTPWIN
    port: 21
    username: ftpunix
    password: 12Xdirect
    drop:
      location: /acad_abc_qa/Export
    
eureka:
  client:
    enabled: true
    service-url:  
      defaultZone: http://uat-oupeureka:8761/eureka/
  instance:
    prefer-ip-address: true    
management:
  security:
    enabled: false
  metrics:
    export:
      prometheus: 
        enabled: true
    distribution:
      percentiles[http.server.requests]: 0.95, 0.99
      percentiles-histogram[http.server.requests]: true
      sla[http.server.requests]: 10ms, 100ms    
---
spring:
  profiles: prod
  activemq:
    broker-url: tcp://gbsmixprd02.uk.oup.com:63636
    user: servicemix
    password: servicemix@1234
  datasource:
    url: jdbc:mysql://GBSMIXDEV01.UK.OUP.COM:3306/sps
    username: SMIXDBUser
    password: P@ssw0rd1!
    driver-class-name: com.mysql.jdbc.Driver

activemq:
    uk:
      queuename: queue:SPS-ACAD-UK-AC18-SAP-TITLES-PRD
      corntab:
        timezone: Europe/London
        starttime: 0 00 22 * * ? *
        stoptime: 0 15 22 * * ? *  
    us:
      queuename: queue:SPS-ACAD-US-US18-SAP-TITLES-PRD
      corntab:
        timezone: US/Hawaii
        starttime: 0 00 22 * * ? *
        stoptime: 0 15 22 * * ? *  
      
file:
  backup:
    location: /OUT/SPS/${spring.application.name}/prod
    

ftp:
  uk: 
    server: GBOXFFTPWIN
    port: 21
    username: ftpunix
    password: 12Xdirect
    drop:
      location: /acad_abc/Export
  us: 
    server: GBOXFFTPWIN
    port: 21
    username: ftpunix
    password: 12Xdirect
    drop:
      location: /acad_abc/Export
management:
  security:
    enabled: false
  metrics:
    export:
      prometheus: 
        enabled: true
    distribution:
      percentiles[http.server.requests]: 0.95, 0.99
      percentiles-histogram[http.server.requests]: true
      sla[http.server.requests]: 10ms, 100ms

 
